language: ruby
sudo: false
bundler_args: --without system_tests
script:
  - "bundle exec puppet --version"
  - "bundle exec rake validate"
  - "bundle exec rake lint"
  - "bundle exec rake spec SPEC_OPTS='--color --format documentation'"
  - '[ "$PUPPET_GEM_VERSION" == ">= 3.7.0" ] && bundle exec rake future || exit 0'
rvm:
 - 1.8.7
 - 1.9.3-p484
 - 2.0.0
 - 2.1.6
env:
 - PUPPET_GEM_VERSION=">= 3.7.0"
matrix:
  fast_finish: true
  allow_failures:
    - env: PUPPET_GEM_VERSION="~> 4.0" ORDERING="random" STRICT_VARIABLES="yes"
  include:
    - rvm: 2.1
      env: PUPPET_GEM_VERSION="~> 4.0" ORDERING="random" STRICT_VARIABLES="yes"
notifications:
  email: false
